//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CID { get; set; }
        public string CName { get; set; }
        public decimal CFee { get; set; }
        public string Technology { get; set; }
        public string Status { get; set; }
    }
}
